# Generated by Django 4.2.4 on 2024-06-13 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 13, 8, 10, 39, 376139, tzinfo=datetime.timezone.utc)),
        ),
    ]
